const supportEmail = "hello@shiftway.app";

const makeFaq = (topic) => [
  {
    question: `What is ${topic.toLowerCase()} in Shiftway?`,
    answer: `${topic} is part of the public Shiftway site so buyers can evaluate product fit, pricing, support, and the broader trust story without guessing.`,
  },
  {
    question: `What should I do next after reading this page?`,
    answer: "Move to pricing, signup, support, or contact depending on whether you are evaluating, rolling out, or troubleshooting.",
  },
];

const makePage = ({ path, groupKey, label, title, description, eyebrow, heroTitle, heroBody, highlights, primary, secondary }) => ({
  path,
  groupKey,
  label,
  title,
  description,
  eyebrow,
  heroTitle,
  heroBody,
  highlights,
  sections: [
    {
      title: `Why ${label.toLowerCase()} matters`,
      body: `${label} is one of the pages buyers and operators expect while evaluating scheduling software for shift-based teams.`,
      bullets: highlights,
    },
    {
      title: "How to use this page",
      body: "Use this page as a clear next step in the buying or rollout journey.",
      bullets: [
        "Review the relevant workflow or trust topic",
        "Share the route with the right buyer or manager",
        "Continue to pricing, signup, or support",
      ],
    },
  ],
  faq: makeFaq(label),
  cta: {
    title: "Keep moving through the evaluation flow",
    body: "Shiftway is structured so buyers can move from overview pages into pricing, signup, or support without losing context.",
    primary,
    secondary,
  },
});

export const marketingPages = [
  makePage({
    path: "/product",
    groupKey: "product",
    label: "Product",
    title: "Shiftway Product | Scheduling, requests, communication, and operations",
    description: "Browse Shiftway product information for scheduling, requests, communication, and team operations.",
    eyebrow: "Product",
    heroTitle: "One scheduling workflow for teams that run on shifts",
    heroBody: "Shiftway brings scheduling, requests, communication, and daily coordination into one operating system.",
    highlights: [
      "Employee scheduling and weekly publishing",
      "Open shifts, swaps, requests, and approvals",
      "Tasks, messaging, and labor visibility",
    ],
    primary: { label: "Start free trial", to: "/signup" },
    secondary: { label: "View pricing", to: "/pricing" },
  }),
  makePage({
    path: "/industries",
    groupKey: "industries",
    label: "Industries",
    title: "Industries | Shiftway scheduling software for shift-based businesses",
    description: "See how Shiftway fits restaurants, retail, healthcare, hospitality, and other shift-based industries.",
    eyebrow: "Industries",
    heroTitle: "Built for industries that live on the schedule",
    heroBody: "Shiftway is designed for teams that need clarity around coverage, requests, labor visibility, and constant schedule change.",
    highlights: [
      "Restaurants, retail, hospitality, and healthcare",
      "Single-location and multi-location teams",
      "Frontline teams with high schedule churn",
    ],
    primary: { label: "Start free trial", to: "/signup" },
    secondary: { label: "Contact us", to: "/contact-us" },
  }),
  makePage({
    path: "/support",
    groupKey: "support",
    label: "Support",
    title: "Shiftway Support | Help, setup, and troubleshooting",
    description: "Find help with setup, troubleshooting, support routing, and common Shiftway questions.",
    eyebrow: "Support",
    heroTitle: "Help for rollout, troubleshooting, and day-to-day use",
    heroBody: "Use Shiftway support pages when you need setup guidance, issue resolution, or a direct path to the team.",
    highlights: [
      "Getting started and rollout help",
      "Workspace troubleshooting and routing",
      "Support requests and product questions",
    ],
    primary: { label: "Contact support", to: "/support/contact-support" },
    secondary: { label: "Help center", to: "/support/help-center" },
  }),
  makePage({
    path: "/resources",
    groupKey: "resources",
    label: "Resources",
    title: "Shiftway Resources | FAQs, security, and trust pages",
    description: "Browse Shiftway resource pages for pricing FAQs, security information, and reference material.",
    eyebrow: "Resources",
    heroTitle: "Reference pages buyers expect to find",
    heroBody: "The resource section gives buyers and admins a clearer view of the trust and decision-support pages around Shiftway.",
    highlights: [
      "Pricing and evaluation FAQs",
      "Security and trust context",
      "Reference pages for buyers and admins",
    ],
    primary: { label: "Read FAQs", to: "/resources/faqs" },
    secondary: { label: "Review security", to: "/resources/security" },
  }),
  makePage({
    path: "/about",
    groupKey: "company",
    label: "About",
    title: "About Shiftway | Scheduling software for hourly teams",
    description: "Learn what Shiftway is built for and why the platform focuses on shift-based team operations.",
    eyebrow: "Company",
    heroTitle: "Built for teams that live on the schedule",
    heroBody: "Shiftway exists to replace spreadsheet-heavy scheduling with a cleaner operating system for frontline teams.",
    highlights: [
      "Built for shift-based teams",
      "Focused on weekly execution, not just planning",
      "Designed to keep managers and employees aligned",
    ],
    primary: { label: "View pricing", to: "/pricing" },
    secondary: { label: "Start free trial", to: "/signup" },
  }),
  makePage({
    path: "/blog",
    groupKey: "company",
    label: "Blog",
    title: "Shiftway Blog | Scheduling, staffing, and frontline operations",
    description: "Explore Shiftway blog positioning for staffing, scheduling, and frontline operations content.",
    eyebrow: "Company",
    heroTitle: "Content for operators who run on shifts",
    heroBody: "The Shiftway blog is the editorial space for staffing, scheduling, and operational guidance.",
    highlights: [
      "Scheduling best practices",
      "Operational advice for managers",
      "Staffing and communication guidance",
    ],
    primary: { label: "View pricing", to: "/pricing" },
    secondary: { label: "Contact us", to: "/contact-us" },
  }),
  makePage({
    path: "/privacy",
    groupKey: "company",
    label: "Privacy Statement",
    title: "Privacy Statement | Shiftway",
    description: "Read the Shiftway privacy statement summary and where to route privacy-related questions.",
    eyebrow: "Trust",
    heroTitle: "How Shiftway approaches privacy questions",
    heroBody: "This page is the starting point for privacy-oriented questions and support routing.",
    highlights: [
      "Privacy requests can be routed through support",
      "Workspace context helps the team review requests",
      "Reference material for buyers and admins",
    ],
    primary: { label: "Contact support", to: "/support/contact-support" },
    secondary: { label: "Email Shiftway", href: `mailto:${supportEmail}` },
  }),
  makePage({
    path: "/terms",
    groupKey: "company",
    label: "Terms",
    title: "Terms | Shiftway",
    description: "Review the Shiftway terms summary and account expectations.",
    eyebrow: "Trust",
    heroTitle: "Shiftway terms summary",
    heroBody: "Use this page as a quick starting point for terms and account-use expectations.",
    highlights: [
      "Account use expectations",
      "Operational and billing context",
      "Support routing for follow-up questions",
    ],
    primary: { label: "Contact support", to: "/support/contact-support" },
    secondary: { label: "View pricing", to: "/pricing" },
  }),
  makePage({
    path: "/cookie-policy",
    groupKey: "company",
    label: "Cookie Policy",
    title: "Cookie Policy | Shiftway",
    description: "Read the Shiftway cookie policy summary for browser storage and session behavior.",
    eyebrow: "Trust",
    heroTitle: "How Shiftway uses cookies and storage",
    heroBody: "This page explains the role of essential browser storage and where to get help if storage behavior affects the app.",
    highlights: [
      "Essential storage supports sign-in and continuity",
      "Session behavior can affect product usage",
      "Support is available for browser-related issues",
    ],
    primary: { label: "Contact support", to: "/support/contact-support" },
    secondary: { label: "Open app", to: "/app" },
  }),
  makePage({
    path: "/contact-us",
    groupKey: "company",
    label: "Contact us",
    title: "Contact Shiftway | Sales, support, and product questions",
    description: "Contact Shiftway for product questions, sales conversations, support issues, and rollout help.",
    eyebrow: "Contact",
    heroTitle: "Talk to the Shiftway team",
    heroBody: "Use this page for pricing conversations, support routing, and broader product questions.",
    highlights: [
      "Sales and pricing questions",
      "Support and rollout help",
      "General product and trust follow-up",
    ],
    primary: { label: "Email Shiftway", href: `mailto:${supportEmail}` },
    secondary: { label: "View pricing", to: "/pricing" },
  }),
  makePage({
    path: "/support/help-center",
    groupKey: "support",
    label: "Help center",
    title: "Help Center | Shiftway",
    description: "Browse Shiftway help-center guidance for setup, rollout, and using the product.",
    eyebrow: "Support",
    heroTitle: "Get a new workspace running faster",
    heroBody: "The help center is the starting point for setup, onboarding, and first-week workflow questions.",
    highlights: [
      "Workspace setup guidance",
      "Invite and rollout support",
      "Schedule publishing basics",
    ],
    primary: { label: "Contact support", to: "/support/contact-support" },
    secondary: { label: "Start free trial", to: "/signup" },
  }),
  makePage({
    path: "/support/contact-support",
    groupKey: "support",
    label: "Contact support",
    title: "Contact Support | Shiftway",
    description: "Reach Shiftway support for troubleshooting, setup help, and workspace issues.",
    eyebrow: "Support",
    heroTitle: "Get product and workspace help",
    heroBody: "Use this route when you need direct help with setup, access, or unexpected workspace behavior.",
    highlights: [
      "Troubleshooting and setup guidance",
      "Workspace and access questions",
      "Support routing for operational issues",
    ],
    primary: { label: "Email support", href: `mailto:${supportEmail}` },
    secondary: { label: "Help center", to: "/support/help-center" },
  }),
  makePage({
    path: "/resources/faqs",
    groupKey: "resources",
    label: "FAQs",
    title: "FAQs | Shiftway",
    description: "Review common questions about Shiftway pricing, rollout, support, and product fit.",
    eyebrow: "Resources",
    heroTitle: "Frequently asked questions about Shiftway",
    heroBody: "This page gives buyers and admins a direct route to common evaluation and rollout questions.",
    highlights: [
      "Questions about pricing and trials",
      "Questions about rollout and support",
      "Questions about product fit",
    ],
    primary: { label: "View pricing", to: "/pricing" },
    secondary: { label: "Start free trial", to: "/signup" },
  }),
  makePage({
    path: "/resources/security",
    groupKey: "resources",
    label: "Security",
    title: "Security | Shiftway",
    description: "Review Shiftway's security overview and where to route deeper security questions.",
    eyebrow: "Resources",
    heroTitle: "Shiftway security overview",
    heroBody: "Use this page as the high-level security reference while evaluating or rolling out the platform.",
    highlights: [
      "Access is tied to authenticated workflows",
      "Roles shape what users can do",
      "Security follow-up can be routed through the team",
    ],
    primary: { label: "Contact us", to: "/contact-us" },
    secondary: { label: "View pricing", to: "/pricing" },
  }),
];

export const marketingNavLinks = [
  { label: "Product", to: "/product" },
  { label: "Industries", to: "/industries" },
  { label: "Resources", to: "/resources" },
  { label: "Support", to: "/support" },
  { label: "Pricing", to: "/pricing" },
];

export const marketingFooterGroups = [
  {
    title: "Company",
    items: [
      { label: "About", to: "/about" },
      { label: "Blog", to: "/blog" },
      { label: "Privacy Statement", to: "/privacy" },
      { label: "Terms", to: "/terms" },
      { label: "Cookie Policy", to: "/cookie-policy" },
    ],
  },
  {
    title: "Explore",
    items: [
      { label: "Product", to: "/product" },
      { label: "Industries", to: "/industries" },
      { label: "Pricing", to: "/pricing" },
      { label: "Contact us", to: "/contact-us" },
    ],
  },
  {
    title: "Support",
    items: [
      { label: "Help center", to: "/support/help-center" },
      { label: "Contact support", to: "/support/contact-support" },
      { label: "Support hub", to: "/support" },
    ],
  },
  {
    title: "Resources",
    items: [
      { label: "Resources hub", to: "/resources" },
      { label: "FAQs", to: "/resources/faqs" },
      { label: "Security", to: "/resources/security" },
      { label: supportEmail, href: `mailto:${supportEmail}` },
    ],
  },
];
