name: CI

on:
  push:
    branches: ["main", "auto/shiftway-release-bot"]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install (frontend + server)
        run: npm run install:all

      - name: Check (build + server install)
        run: npm run ci
